name: Build FridaGadget

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Theos
        uses: Randomblock1/theos-action@v1.4
        with:
          # Where to install Theos
          theos-dir: ${{ github.workspace }}/theos
          # Where to clone Theos from (git URL)
          theos-src: https://github.com/theos/theos
          # Where to clone the iOS SDKs from (GitHub repository URL)
          theos-sdks: https://github.com/theos/sdks
          # Which branch to clone from SDK repo
          theos-sdks-branch: master
          # Whether to enable Orion, which adds support for Swift tweaks
          orion: false

      - name: Build package
        working-directory: FridaGadgetLoader
        run: |
          make clean
          make package FINALPACKAGE=1

      - uses: actions/upload-artifact@v4
        with:
          name: FridaGadgetLoader
          path: FridaGadgetTweak/packages/*.deb
