name: Build FridaGadget Loader

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-deb:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Theos
        uses: Randomblock1/theos-action@v1

      - name: Build Package
        run: |
          cd FridaGadgetLoader
          make clean
          make package FINALPACKAGE=1

      - name: Upload DEB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: FridaGadgetLoader_${{ github.sha }}
          path: FridaGadgetLoader/packages/*.deb
          retention-days: 7
